name: Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: ghcr.io/blueoceanideas/stack-deployer
        username: ${{ secrets.DOCKER_BUILD_GITHUB_SECRET }}
        password: ${{ secrets.DOCKER_GITHUB_USER }}
        registry: ghcr.io
